format = """
\\[[$username](bold yellow)[@$hostname](bold yellow)[ $directory](bold cyan)[$git_branch](bold purple)[$git_status](bold red)[$cmd_duration](yellow)\\]
$character"""

[username]
format = "[$user]($style)"
style_user = "bold yellow"
show_always = true

[hostname]
format = "[@$hostname]($style)"
style = "bold yellow"
ssh_only = false

[directory]
format = "[ in $path]($style)"
style = "bold cyan"
truncate_to_repo = false
truncation_length = 3

[git_branch]
format = "[ $symbol$branch]($style)"
style = "bold purple"
symbol = " "

[git_status]
format = '([ $all_status$ahead_behind]($style))'
style = "bold red"

[cmd_duration]
format = "[ took $duration]($style)"
style = "yellow"
min_time = 0

[character]
success_symbol = "[}](bold cyan)"
error_symbol = "[}](bold red)"
