-- Generated by matugen from your wallpaper. Do not edit manually.
-- Regenerated automatically each time you pick a wallpaper (SUPER+W → matugen image).
-- Colors are Material Design 3 tokens extracted from the wallpaper's dominant palette.
return {
    outline             = "rgba({{ colors.outline.default.hex_stripped }}ff)",
    outline_variant     = "rgba({{ colors.outline_variant.default.hex_stripped }}ff)",
    primary             = "rgba({{ colors.primary.default.hex_stripped }}ff)",
    primary_container   = "rgba({{ colors.primary_container.default.hex_stripped }}ff)",
    secondary           = "rgba({{ colors.secondary.default.hex_stripped }}ff)",
    surface             = "rgba({{ colors.surface.default.hex_stripped }}ff)",
    surface_container   = "rgba({{ colors.surface_container.default.hex_stripped }}ff)",
    source_color        = "rgba({{ colors.source_color.default.hex_stripped }}ff)",
}
