-- Generated by scheme-apply.sh — do not edit manually.
return {{
    bg4      = "rgba({bg4.strip}ff)",
    bg3      = "rgba({bg3.strip}ff)",
    red      = "rgba({red.strip}ff)",
    dark_red = "rgba({dark_red.strip}ff)",
    blue     = "rgba({blue.strip}ff)",
    bg       = "rgba({bg.strip}ff)",
    bg2      = "rgba({bg2.strip}ff)",
    white    = "rgba(ffffffff)",
    black    = "rgba(000000ff)",
    accent   = "rgba({accent.strip}ff)",
}}
