$image = {wallpaper}

$bg      = rgba({bg.strip}ff)
$bg_h    = rgba({bg_h.strip}ff)
$bg_s    = rgba({bg_s.strip}ff)
$bg0     = rgba({bg0.strip}ff)
$bg1     = rgba({bg1.strip}ff)
$bg2     = rgba({bg2.strip}ff)
$bg3     = rgba({bg3.strip}ff)
$bg4     = rgba({bg4.strip}ff)
$fg      = rgba({fg.strip}ff)
$fg0     = rgba({fg0.strip}ff)
$fg1     = rgba({fg1.strip}ff)
$fg2     = rgba({fg2.strip}ff)
$fg3     = rgba({fg3.strip}ff)
$fg4     = rgba({fg4.strip}ff)
$gray0   = rgba({gray0.strip}ff)
$gray1   = rgba({gray1.strip}ff)
$gray2   = rgba({gray2.strip}ff)
$red     = rgba({red.strip}ff)
$green   = rgba({green.strip}ff)
$yellow  = rgba({yellow.strip}ff)
$blue    = rgba({blue.strip}ff)
$purple  = rgba({purple.strip}ff)
$aqua    = rgba({aqua.strip}ff)
$orange  = rgba({orange.strip}ff)
$dark_red     = rgba({dark_red.strip}ff)
$dark_green   = rgba({dark_green.strip}ff)
$dark_yellow  = rgba({dark_yellow.strip}ff)
$dark_blue    = rgba({dark_blue.strip}ff)
$dark_purple  = rgba({dark_purple.strip}ff)
$dark_aqua    = rgba({dark_aqua.strip}ff)
$dark_orange  = rgba({dark_orange.strip}ff)
$white        = rgba(ffffffff)
$black        = rgba(000000ff)
$accent       = rgba({accent.strip}ff)
