background {bg}
foreground {kitty_fg}
cursor     {kitty_fg}

color0  {bg}
color1  {dark_red}
color2  {dark_green}
color3  {dark_yellow}
color4  {dark_blue}
color5  {dark_purple}
color6  {dark_aqua}
color7  {gray2}
color8  {bg3}
color9  {red}
color10 {green}
color11 {yellow}
color12 {blue}
color13 {purple}
color14 {aqua}
color15 {fg}

selection_background {dark_red}
selection_foreground {bg}
